name: Build RocksDB Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android tools
        run: |
          sdkmanager "platform-tools" \
            "platforms;android-35" \
            "build-tools;35.0.0" \
            "cmake;3.31.6" \
            "ndk;29.0.14206865"

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew :library:assembleRelease

      - name: Upload AAR
        uses: actions/upload-artifact@v4
        with:
          name: rocksdb-android-aar
          path: library/build/outputs/aar/*.aar
